name: Build and Push Docker

on:
  workflow_call:
    inputs:
      directory:
        description: 'The directory to build'
        required: true
        type: string
      ecr_repository:
        description: 'The ECR repository name'
        required: true
        type: string
      paths:
        description: 'Paths to monitor for changes'
        required: true
        type: string
      always_build:
        description: 'Always build, irrespective of paths'
        required: false
        type: boolean

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    environment: Blogapp 
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' && ( inputs.always_build == true || (inputs.paths != '' && github.event.commits.*.modified contains inputs.paths)) }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Log in to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build and push Docker image
      run: |
        docker build -t ${{ inputs.ecr_repository }}:latest ./${{ inputs.directory }}
        docker tag ${{ inputs.ecr_repository }}:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ inputs.ecr_repository }}:latest
        docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ inputs.ecr_repository }}:latest
